# Generated by Django 5.1.3 on 2024-12-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aonewebs', '0003_alter_aoneeducational_exam_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoneeducational',
            name='olevel_sub_eig',
            field=models.CharField(choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, verbose_name="O'Level Subject 8"),
        ),
        migrations.AlterField(
            model_name='aoneeducational',
            name='olevel_sub_five',
            field=models.CharField(choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, verbose_name="O'Level Subject 5"),
        ),
        migrations.AlterField(
            model_name='aoneeducational',
            name='olevel_sub_four',
            field=models.CharField(choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, verbose_name="O'Level Subject 4"),
        ),
        migrations.AlterField(
            model_name='aoneeducational',
            name='olevel_sub_nin',
            field=models.CharField(choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, verbose_name="O'Level Subject 9"),
        ),
        migrations.AlterField(
            model_name='aoneeducational',
            name='olevel_sub_one',
            field=models.CharField(choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, verbose_name="O'Level Subject 1"),
        ),
        migrations.AlterField(
            model_name='aoneeducational',
            name='olevel_sub_sev',
            field=models.CharField(choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, verbose_name="O'Level Subject 7"),
        ),
        migrations.AlterField(
            model_name='aoneeducational',
            name='olevel_sub_six',
            field=models.CharField(choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, verbose_name="O'Level Subject 6"),
        ),
        migrations.AlterField(
            model_name='aoneeducational',
            name='olevel_sub_three',
            field=models.CharField(choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, verbose_name="O'Level Subject 3"),
        ),
        migrations.AlterField(
            model_name='aoneeducational',
            name='olevel_sub_two',
            field=models.CharField(choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, verbose_name="O'Level Subject 2"),
        ),
        migrations.AlterField(
            model_name='aoneeducational',
            name='utme_sub_four',
            field=models.CharField(blank=True, choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, null=True, verbose_name='UTME subject 4'),
        ),
        migrations.AlterField(
            model_name='aoneeducational',
            name='utme_sub_one',
            field=models.CharField(blank=True, choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, null=True, verbose_name='UTME subject 1'),
        ),
        migrations.AlterField(
            model_name='aoneeducational',
            name='utme_sub_three',
            field=models.CharField(blank=True, choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, null=True, verbose_name='UTME subject 3'),
        ),
        migrations.AlterField(
            model_name='aoneeducational',
            name='utme_sub_two',
            field=models.CharField(blank=True, choices=[('Use of English Language', 'Use of English Language'), ('English Language', 'English Language'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Studies', 'Computer Studies'), ('Physical Health Education', 'Physical Health Education'), ('Literature in English', 'Literature in English'), ('Home Economics', 'Home Economics'), ('History', 'History'), ('Hausa', 'Hausa'), ('Government', 'Government'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Christain Religious Education', 'Christain Religious Education'), ('Commerce', 'Commerce'), ('Biology', 'Biology'), ('Agricultural Science', 'Agricultural Science'), ('Accounting', 'Accounting'), ('French', 'French'), ('Arabic', 'Arabic'), ('Yoruba', 'Yoruba'), ('Civic Education', 'Civic Education')], max_length=200, null=True, verbose_name='UTME subject 2'),
        ),
    ]
